name: Lint

on:
  workflow_dispatch:
    inputs:
      lint_format:
        description: 'Run with format'
        required: false
        default: true
        type: boolean
      pr_number:
        description: 'Pull Request Number'
        required: true
        type: number
      retry_count:
        description: "Number of retries for Unity commands"
        required: false
        default: 5
        type: number
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
      - main
    paths:
      - 'Assets/**'
      - 'Packages/**'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash


jobs:
  lint:
    name: Quality Check
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-6000.2.6f2-linux-il2cpp-3.1.0
    permissions:
      contents: write
      pull-requests: write
      issues: read
      checks: write
    env:
      LINT_FORMAT: ${{ inputs.lint_format || true }}
      TARGET_PATH: ./Assets/JJJ/
      PR_NUMBER: ${{ inputs.pr_number || github.event.pull_request.number }}
      RETRY_COUNT: ${{ inputs.retry_count || 5 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Check Unity Meta Files
        uses: DeNA/unity-meta-check@v4
        with:
          enable_pr_comment: true
          pr_comment_lang: ja
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Git Credentials
        run: |
          git config --global url."https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('Packages/manifest.json', 'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ runner.os }}-
            Library-

      - name: Generate Solution
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        run: |
          retry_command() {
            local max_attempts="${RETRY_COUNT:-5}"
            local attempt=1
            
            while [ $attempt -le $max_attempts ]; do
              echo "Attempt $attempt/$max_attempts: $*"
              if "$@"; then
                echo "Command succeeded on attempt $attempt"
                return 0
              else
                echo "Command failed on attempt $attempt"
                if [ $attempt -eq $max_attempts ]; then
                  echo "Command failed after $max_attempts attempts"
                  return 1
                fi
                sleep $((attempt * 5))
                attempt=$((attempt + 1))
              fi
            done
          }

          retry_command unity-editor -nographics -quit -username "$UNITY_EMAIL" -password "$UNITY_PASSWORD" -serial "$UNITY_SERIAL" -batchmode -logFile /dev/stdout
          retry_command unity-editor -nographics -projectPath . -executeMethod Packages.Rider.Editor.RiderScriptEditor.SyncSolution -quit -batchmode -logFile /dev/stdout

      - name: Setup .NET
        run: |
          wget https://dot.net/v1/dotnet-install.sh -qO dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --channel 8.0 --install-dir $HOME/.dotnet
          echo "$HOME/.dotnet" >> $GITHUB_PATH
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Run Lint
        id: lint
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
          DOTNET_NOLOGO: 1
        run: |
          LINT_FORMAT="${LINT_FORMAT:-true}"
          SLN_FILE=$(find . -name "*.sln" | head -n 1)
          if [ -z "$SLN_FILE" ] || [ ! -f "$SLN_FILE" ]; then
            echo "No solution file found. Exiting."
            exit 1
          fi
          if [ -z "$TARGET_PATH" ] || [ ! -d "$TARGET_PATH" ]; then
            echo "No target path specified. Exiting."
            exit 1
          fi
          if [ "$LINT_FORMAT" = "false" ]; then
            echo "Checking style without format."
            dotnet format "$SLN_FILE" style --verify-no-changes --verbosity quiet --include "$TARGET_PATH" > format.log 2>&1 || true
            cat format.log | sed -E "s|^$(pwd)/||; \
              s/\\(([0-9]+),([0-9]+)\\):/:\\1:\\2:/; \
              s/\\[.*\\]//; \
              s/: warning /: W /; \
              s/: error /: E /" \
            > formatted.log
            if [ -s formatted.log ]; then
              echo "Linting issues found:"
              cat formatted.log
              echo "lint=true" >> $GITHUB_OUTPUT
            else
              echo "No linting issues found."
              echo "lint=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "Checking style with format."
            dotnet format "$SLN_FILE" style --verbosity quiet --include "$TARGET_PATH" > format.log 2>&1 || true
            git diff --shortstat "$TARGET_PATH"
            echo "lint=false" >> $GITHUB_OUTPUT
          fi
          

      - name: Setup Reviewdog
        if: steps.lint.outputs.lint == 'true' && env.LINT_FORMAT == 'false'
        uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893
        with:
          reviewdog_version: latest

      - name: Review with reviewdog
        if: steps.lint.outputs.lint == 'true' && env.LINT_FORMAT == 'false'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat formatted.log | reviewdog -efm="%f:%l:%c: %t %m" -reporter=github-pr-review -fail-level=error -name=dotnet-format -level=warning 
      
      - name: Format Check and Commit
        run: |
          if [ "${LINT_FORMAT}" = "false" ]; then
            echo "Check only, skipping commit."
            exit 0
          fi
          set +e
          git diff --exit-code "$TARGET_PATH"
          if [ $? -ne 0 ]; then
            echo "Linting issues found, committing changes."
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add "$TARGET_PATH"
            git commit -m "format: fix linting issues"
            git push
          else
            echo "No linting issues found, no changes to commit."
          fi

      - name: Run Unity Tests
        id: unity-tests
        run: |
          unity-editor -nographics -logFile /dev/stdout -projectPath . -runTests -testPlatform editmode -testResults ./test-results/TestResults_editmode.xml
          unity-editor -nographics -logFile /dev/stdout -projectPath . -runTests -testPlatform playmode -testResults ./test-results/TestResults_playmode.xml
          echo "Unity tests completed."
          if [ -s ./test-results/TestResults_editmode.xml ] || [ -s ./test-results/TestResults_playmode.xml ]; then
            echo "Unity tests found issues."
            echo "unity_tests=true" >> $GITHUB_OUTPUT
          else
            echo "No Unity test issues found."
            echo "unity_tests=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Unity Tests Result
        if: (!cancelled() && steps.unity-tests.outputs.unity_tests == 'true')
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            test-results/**/*.xml
          check_name: "Unity Tests"
          action_fail: true
