name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop

jobs:
  lint:
    name: Quality Check
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-6000.1.7f1-linux-il2cpp-3
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Solution
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        run: |
          unity-editor -nographics -logFile /dev/stdout -quit -username "$UNITY_EMAIL" -password "$UNITY_PASSWORD" -serial "$UNITY_SERIAL"
          unity-editor -nographics -logFile /dev/stdout -customBuildName JJJ -projectPath . -executeMethod Packages.Rider.Editor.RiderScriptEditor.SyncSolution -quit

      - name: Setup .NET
        run: |
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --channel 8.0 --install-dir $HOME/.dotnet
          echo "$HOME/.dotnet" >> $GITHUB_PATH
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Run Lint
        run: |
          dotnet format JJJ.sln style --verify-no-changes --verbosity diagnostic --include ./Assets/JJJ/
